### ISSUE TITLE
[시스템]프로그램 내 색상표 버그

### ISSUE THREAD

**Issue by ycs-202007005** [poro912/yuhan_guest_book#19]
![캡처](https://user-images.githubusercontent.com/71325061/132128476-3b60df07-dd8c-4c71-a47d-a25ecbc52987.PNG)
![캡처1](https://user-images.githubusercontent.com/71325061/132128477-8c50d70d-b32c-456b-892c-00506b1d3717.PNG)
코드상으로는 색상이 표시되어야 하나, 프로그램을 실행시키면 표시되어야 할 색버튼이 보이지 않습니다.
하지만 보이지만 않는 것이라 화살표로 표시한 부분을 클릭을 하면 펜의 색이 바뀌긴 합니다.

**Comment by poro912** [comment]
그래픽에서 담당하는 반복문의 i 값이 1부터 시작해서 생기는 버그였습니다 현재 버그 픽스 완료 했으며 
모듈화 진행하여 완료 하였습니다.
