### ISSUE TITLE
[시스템] 지우개 사용 변경

### ISSUE THREAD

**Issue by ckdduf138** [poro912/yuhan_guest_book#23]
지우개 사용 시 흰색으로 덧칠하는 방식으로 코딩이 되어 있는 상태입니다.
지우개를 사용했을 경우 흰색으로 덧칠하는 방식이 아닌 데이터를 삭제하는 방식 혹은
다른 방식으로 구현해야 합니다.
리플레이 했을 경우 최종적으로 남는 데이터만 리플레이 해야 합니다.

**Comment by poro912** [comment]
제가 생각한건 세가지 형태의 지우개 입니다.
벡터 지우개
선 지우개
1. 일반 지우개 
벡터상으로 지워지지 않으며 펜과 분리되어 흰색 선을 그리기만 하는 방식으로 작동합니다.
또한 펜을 선택했을때와는 다른 크기로 설정되며 펜과 지우개를 오가며  크기가 설정되게 하는 방식으로 하면 어떨까 하는 생각입니다.
ex)
펜 10px
지우개 30px
지우개 버튼을 누르면 30px과 흰색 색상으로 펜을 그림
이후 펜을 다시 누르면 10px의 기존 색상으로 펜을 그림

2. 벡터 지우개
위와 같은 형식이지만 벡터에서 데이터를 지우는 방식입니다
이 경우 현재의 시스템인 왼쪽마우스 Down 과 Up 에서 시간차이를 구분하지 못하여 오랜시간 대기하게되는 문제를 야기 할 수 있어 여러 제약이 생깁니다

3.선 지우개
아이패드의 지우개 방식으로 선을 그려놓고 지우개로 선의 일부를 지우면 한 획으로 그려진 선 전체가 지워지는 형태의 지우개 입니다. 

구현 난이도는 일반지우개 < 선지우개 < 벡터 지우개이며 차후 세 기능을 모두 만들어 적용 하거나 가장 효휼이 좋은 지우개를 선택해 올릴 예정입니다.

**Comment by poro912** [comment]
교수님이 지우개 관련해서는 필요 없을거같다 판단하셔서 해당 이슈는 삭제처리했습니다.
