### ISSUE TITLE
[시스템] REPALY버튼 누를때 버그

### ISSUE THREAD

**Issue by ckdduf138** [poro912/yuhan_guest_book#31]
REPALY 할 때 팔레트를 누르면 없어지는 버그는 수정 되었으나,
[+], [-] 버튼을 누를 때에도 없어지는 버그가 있습니다.

**Comment by poro912** [comment]
아마 [+] [-] 버튼을 누를시 InvalidateRect함수의 범위가 특정 범위가 아닌 전체 범위에 있어서 그럴것으로 예상됩니다.
